import {
	Activity,
	BadgeCheck,
	Banknote,
	Briefcase,
	Building2,
	CalendarX,
	Car,
	CheckCircle,
	CircleDollarSign,
	Clock,
	CloudRain,
	Cog,
	Droplets,
	FileText,
	Flame,
	Gavel,
	Globe,
	HardDrive,
	Headset,
	Heart,
	HeartHandshake,
	Home,
	Key,
	Laptop,
	Lock,
	Luggage,
	MapPin,
	MapPinHouse,
	Plane,
	Scale,
	Settings,
	Shield,
	SlidersVertical,
	Stethoscope,
	TrendingUp,
	Umbrella,
	Users,
	Wrench,
	Zap,
} from 'lucide-react'

export const translateIcon = {
	Activity: Activity,
	BadgeCheck: BadgeCheck,
	BankNote: Banknote,
	Banknote: Banknote,
	Briefcase: Briefcase,
	Building2: Building2,
	CalendarX: CalendarX,
	Car: Car,
	CheckCircle: CheckCircle,
	CircleDolarSign: CircleDollarSign,
	Clock: Clock,
	CloudRain: CloudRain,
	Cog: Cog,
	Droplets: Droplets,
	FileText: FileText,
	Flame: Flame,
	Gavel: Gavel,
	Globe: Globe,
	HardDrive: HardDrive,
	Headset: Headset,
	Heart: Heart,
	HeartHandshake: HeartHandshake,
	House: Home,
	Key: Key,
	Laptop: Laptop,
	Lock: Lock,
	Luggage: Luggage,
	MapPin: MapPin,
	MapPinHouse: MapPinHouse,
	Plane: Plane,
	Scale: Scale,
	Settings: Settings,
	Shield: Shield,
	SlidersVertical: SlidersVertical,
	Stethoscope: Stethoscope,
	TrendingUp: TrendingUp,
	Umbrella: Umbrella,
	Users: Users,
	Wrench: Wrench,
	Zap: Zap,
}
