/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as adminLayoutRouteImport } from './routes/(admin)/_layout'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as adminLayoutAdminRouteImport } from './routes/(admin)/_layout/admin'
import { Route as publicLayoutIndexRouteImport } from './routes/(public)/_layout/index'
import { Route as publicLayoutServiceRouteImport } from './routes/(public)/_layout/$service'
import { Route as publicLayoutAssistenciaRouteImport } from './routes/(public)/_layout/assistencia'
import { Route as publicLayoutNossaEquipeRouteImport } from './routes/(public)/_layout/nossa-equipe'
import { Route as publicLayoutPremiacoesRouteImport } from './routes/(public)/_layout/premiacoes'
import { Route as publicLayoutTrabalheConoscoRouteImport } from './routes/(public)/_layout/trabalhe-conosco'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutAdminRoute = adminLayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => adminLayoutRoute,
} as any)
const publicLayoutIndexRoute = publicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutServiceRoute = publicLayoutServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutAssistenciaRoute = publicLayoutAssistenciaRouteImport.update({
  id: '/assistencia',
  path: '/assistencia',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutNossaEquipeRoute = publicLayoutNossaEquipeRouteImport.update({
  id: '/nossa-equipe',
  path: '/nossa-equipe',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutPremiacoesRoute = publicLayoutPremiacoesRouteImport.update({
  id: '/premiacoes',
  path: '/premiacoes',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutTrabalheConoscoRoute =
  publicLayoutTrabalheConoscoRouteImport.update({
    id: '/trabalhe-conosco',
    path: '/trabalhe-conosco',
    getParentRoute: () => publicLayoutRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file': typeof ApiFileRoute
  '/admin': typeof adminLayoutAdminRoute
  '/$service': typeof publicLayoutServiceRoute
  '/assistencia': typeof publicLayoutAssistenciaRoute
  '/nossa-equipe': typeof publicLayoutNossaEquipeRoute
  '/premiacoes': typeof publicLayoutPremiacoesRoute
  '/trabalhe-conosco': typeof publicLayoutTrabalheConoscoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/file': typeof ApiFileRoute
  '/admin': typeof adminLayoutAdminRoute
  '/$service': typeof publicLayoutServiceRoute
  '/assistencia': typeof publicLayoutAssistenciaRoute
  '/nossa-equipe': typeof publicLayoutNossaEquipeRoute
  '/premiacoes': typeof publicLayoutPremiacoesRoute
  '/trabalhe-conosco': typeof publicLayoutTrabalheConoscoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(admin)/_layout': typeof adminLayoutRouteWithChildren
  '/(public)/_layout': typeof publicLayoutRouteWithChildren
  '/api/file': typeof ApiFileRoute
  '/(admin)/_layout/admin': typeof adminLayoutAdminRoute
  '/(public)/_layout/$service': typeof publicLayoutServiceRoute
  '/(public)/_layout/assistencia': typeof publicLayoutAssistenciaRoute
  '/(public)/_layout/nossa-equipe': typeof publicLayoutNossaEquipeRoute
  '/(public)/_layout/premiacoes': typeof publicLayoutPremiacoesRoute
  '/(public)/_layout/trabalhe-conosco': typeof publicLayoutTrabalheConoscoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(public)/_layout/': typeof publicLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file'
    | '/admin'
    | '/$service'
    | '/assistencia'
    | '/nossa-equipe'
    | '/premiacoes'
    | '/trabalhe-conosco'
    | '/api/auth/$'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/file'
    | '/admin'
    | '/$service'
    | '/assistencia'
    | '/nossa-equipe'
    | '/premiacoes'
    | '/trabalhe-conosco'
    | '/api/auth/$'
    | '/'
  id:
    | '__root__'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(admin)/_layout'
    | '/(public)/_layout'
    | '/api/file'
    | '/(admin)/_layout/admin'
    | '/(public)/_layout/$service'
    | '/(public)/_layout/assistencia'
    | '/(public)/_layout/nossa-equipe'
    | '/(public)/_layout/premiacoes'
    | '/(public)/_layout/trabalhe-conosco'
    | '/api/auth/$'
    | '/(public)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  ApiFileRoute: typeof ApiFileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout': {
      id: '/(admin)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/admin': {
      id: '/(admin)/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminLayoutAdminRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(public)/_layout/': {
      id: '/(public)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicLayoutIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/$service': {
      id: '/(public)/_layout/$service'
      path: '/$service'
      fullPath: '/$service'
      preLoaderRoute: typeof publicLayoutServiceRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/assistencia': {
      id: '/(public)/_layout/assistencia'
      path: '/assistencia'
      fullPath: '/assistencia'
      preLoaderRoute: typeof publicLayoutAssistenciaRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/nossa-equipe': {
      id: '/(public)/_layout/nossa-equipe'
      path: '/nossa-equipe'
      fullPath: '/nossa-equipe'
      preLoaderRoute: typeof publicLayoutNossaEquipeRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/premiacoes': {
      id: '/(public)/_layout/premiacoes'
      path: '/premiacoes'
      fullPath: '/premiacoes'
      preLoaderRoute: typeof publicLayoutPremiacoesRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/trabalhe-conosco': {
      id: '/(public)/_layout/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof publicLayoutTrabalheConoscoRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface adminLayoutRouteChildren {
  adminLayoutAdminRoute: typeof adminLayoutAdminRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminLayoutAdminRoute: adminLayoutAdminRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicLayoutServiceRoute: typeof publicLayoutServiceRoute
  publicLayoutAssistenciaRoute: typeof publicLayoutAssistenciaRoute
  publicLayoutNossaEquipeRoute: typeof publicLayoutNossaEquipeRoute
  publicLayoutPremiacoesRoute: typeof publicLayoutPremiacoesRoute
  publicLayoutTrabalheConoscoRoute: typeof publicLayoutTrabalheConoscoRoute
  publicLayoutIndexRoute: typeof publicLayoutIndexRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLayoutServiceRoute: publicLayoutServiceRoute,
  publicLayoutAssistenciaRoute: publicLayoutAssistenciaRoute,
  publicLayoutNossaEquipeRoute: publicLayoutNossaEquipeRoute,
  publicLayoutPremiacoesRoute: publicLayoutPremiacoesRoute,
  publicLayoutTrabalheConoscoRoute: publicLayoutTrabalheConoscoRoute,
  publicLayoutIndexRoute: publicLayoutIndexRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
  ApiFileRoute: ApiFileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
