/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as publiclayoutLayoutRouteImport } from './routes/(public)/(layout)/_layout'
import { Route as adminlayoutLayoutRouteImport } from './routes/(admin)/(layout)/_layout'
import { Route as publiclayoutLayoutIndexRouteImport } from './routes/(public)/(layout)/_layout.index'
import { Route as adminlayoutLayoutAdminRouteImport } from './routes/(admin)/(layout)/_layout.admin'

const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publiclayoutLayoutRoute = publiclayoutLayoutRouteImport.update({
  id: '/(public)/(layout)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const adminlayoutLayoutRoute = adminlayoutLayoutRouteImport.update({
  id: '/(admin)/(layout)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publiclayoutLayoutIndexRoute = publiclayoutLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publiclayoutLayoutRoute,
} as any)
const adminlayoutLayoutAdminRoute = adminlayoutLayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => adminlayoutLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof adminlayoutLayoutAdminRoute
  '/': typeof publiclayoutLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof adminlayoutLayoutAdminRoute
  '/': typeof publiclayoutLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/(layout)/_layout': typeof adminlayoutLayoutRouteWithChildren
  '/(public)/(layout)/_layout': typeof publiclayoutLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(admin)/(layout)/_layout/admin': typeof adminlayoutLayoutAdminRoute
  '/(public)/(layout)/_layout/': typeof publiclayoutLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/auth/$' | '/admin' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/auth/$' | '/admin' | '/'
  id:
    | '__root__'
    | '/(admin)/(layout)/_layout'
    | '/(public)/(layout)/_layout'
    | '/api/auth/$'
    | '/(admin)/(layout)/_layout/admin'
    | '/(public)/(layout)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminlayoutLayoutRoute: typeof adminlayoutLayoutRouteWithChildren
  publiclayoutLayoutRoute: typeof publiclayoutLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(layout)/_layout': {
      id: '/(public)/(layout)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publiclayoutLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/(layout)/_layout': {
      id: '/(admin)/(layout)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminlayoutLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(layout)/_layout/': {
      id: '/(public)/(layout)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publiclayoutLayoutIndexRouteImport
      parentRoute: typeof publiclayoutLayoutRoute
    }
    '/(admin)/(layout)/_layout/admin': {
      id: '/(admin)/(layout)/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminlayoutLayoutAdminRouteImport
      parentRoute: typeof adminlayoutLayoutRoute
    }
  }
}

interface adminlayoutLayoutRouteChildren {
  adminlayoutLayoutAdminRoute: typeof adminlayoutLayoutAdminRoute
}

const adminlayoutLayoutRouteChildren: adminlayoutLayoutRouteChildren = {
  adminlayoutLayoutAdminRoute: adminlayoutLayoutAdminRoute,
}

const adminlayoutLayoutRouteWithChildren =
  adminlayoutLayoutRoute._addFileChildren(adminlayoutLayoutRouteChildren)

interface publiclayoutLayoutRouteChildren {
  publiclayoutLayoutIndexRoute: typeof publiclayoutLayoutIndexRoute
}

const publiclayoutLayoutRouteChildren: publiclayoutLayoutRouteChildren = {
  publiclayoutLayoutIndexRoute: publiclayoutLayoutIndexRoute,
}

const publiclayoutLayoutRouteWithChildren =
  publiclayoutLayoutRoute._addFileChildren(publiclayoutLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  adminlayoutLayoutRoute: adminlayoutLayoutRouteWithChildren,
  publiclayoutLayoutRoute: publiclayoutLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
